### ISSUE TITLE
Migrate into JuliaPlasma

### ISSUE THREAD

**Issue by Beforerr** [JuliaPlasma/ChargedParticles.jl#6]
https://github.com/JuliaPlasma

Ref:

https://github.com/JuliaRegistries/General#how-do-i-transfer-a-package-to-an-organization-or-another-user

**Comment by Beforerr** [comment]
Related to https://github.com/JuliaRegistries/General/pull/120849

**Comment by Beforerr** [comment]
@adamslc Hi Luke, maybe you could help change the url

![image](https://github.com/user-attachments/assets/1a9fc8e8-a201-4632-94e8-35a47a58112d)

**Comment by adamslc** [comment]
Hmm, I also don't seem to have permissions. @michakraus, can you change the repo url?

**Comment by michakraus** [comment]
Done. Also I gave @Beforerr admin rights to his own repo 😉 . Not sure why that wasn't automatic...
